AppSettings:
  SiteTitle: This is the staging application file
  CacheDbResults: true
Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Debug
    System: Information
    Microsoft: Information
eureka:
  client:
    serviceUrl:
      defaultZone: https://csi-eureka-server.run.aws-usw02-pr.ice.predix.io/eureka/
mysql:
  client:
    server: localhost
redis:
  client:
    host: localhost
