AppSettings:
  SiteTitle: This is the development application file - LAB Module
  TemplateID: csi-template-new
  CacheDbResults: true
Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Debug
    System: Information
    Microsoft: Information
ConnectionStrings:
  DB: PatientDB
    WriteCon: PatientDBWrite
    ReadCon: PatientDBRead
  DB: LabDB
    WriteCon: LabDBWrite
    ReadCon: LabDBRead
eureka:
  client:
    serviceUrl:
      defaultZone: https://csi-eureka-server.run.aws-usw02-pr.ice.predix.io/eureka
mysql:
  client:
    server: localhost
redis:
  client:
    host: localhost
