AppSettings:
  SiteTitle: This is the common application file
  CacheDbResults: true
Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Debug
    System: Information
    Microsoft: Information

eureka:
  client:
    serviceUrl:
      defaultZone: https://csi-eureka-server.run.aws-usw02-pr.ice.predix.io:8761/eureka/
    registerWithEureka: true
    fetchRegistry: false
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true
  server:
    enableSelfPreservation: false
mysql:
  client:
    server: localhost
redis:
  client:
    host: localhost
    
module:
  location:
    module: 'ordersubModule'
    parent: 'labModule'
