AppSettings:
  SiteTitle: This is the application file for servers
  TemplateID: csi-template-new
  CacheDbResults: true
Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Debug
    System: Information
    Microsoft: Information
eureka:
  client:
    serviceUrl:
      defaultZone: https://csi-eurekaserver-qa.run.aws-usw02-pr.ice.predix.io/eureka
    registerWithEureka: true
    fetchRegistry: true
mysql:
  client:
    server: localhost
redis:
  client:
    host: localhost
